### ISSUE TITLE
The Self Driving car is demo broken

### ISSUE THREAD

**Issue by VatsaDev** [GabrielTavernini/NeatJS#3]
As the title says, the self drving demo isn't working, its just a blank screen

**Comment by GabrielTavernini** [comment]
Thanks for letting me know! Should be fixed now.

**Comment by GabrielTavernini** [comment]
Fixed with commit [df18a5a](https://github.com/GabrielTavernini/NeatJS/commit/df18a5a4b7b255581b99727e9a47c4ec3e6ed22a)
